name: Integration testing

on:
  push:
    branches: [master, test_with_script]
  pull_request:
    branches: [master]
  schedule:
    - cron: '30 1 1,15 * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { LN_IMPL: ldk}
    steps:
      - uses: actions/checkout@v2
      - name: Integration testing
        run: |
          docker build -f docker/Dockerfile.${{matrix.LN_IMPL}} -t lnprototest-${{matrix.LN_IMPL}} .
          docker run lnprototest-${{matrix.LN_IMPL}}
